### ISSUE TITLE
FlowRouter 2

### ISSUE THREAD

**Issue by johanbuys** [txs/meteor-wecare-ionic-flow#1]
Hi,

I was wondering if there is a specific reason why you are still on V1.9.0 of flowrouter

``` javascript
 api.use(["templating", "underscore", "fastclick", "meteorhacks:flow-router@1.9.0", "arillo:flow-router-helpers@0.4.5", "tracker", "session"], "client");
```

FlowRouter is at ("kadira:flow-router@2.6.2")

With the release of v2 the package have also been renamed see https://github.com/kadirahq/flow-router#migrating-into-20

**Comment by txs** [comment]
Thanks for asking I will test it!

_Sincerely,_

_Andy Tseng 曾郁翔_
_Founder_ & _CEO_ of _WeCare http://signup.wecare.im/_
_Researcher_ @ _Mobile HCI LAB, NTU http://www.ntumobile.org/_
_ME students_ @ _NTU_
_Lindedin_: http://tw.linkedin.com/in/andytseng08/
_FB_: fb.com/andyt08

Sent from wecare www.getwecare.com

2015-10-13 17:00 GMT+08:00 Johan Buys notifications@github.com:

**Comment by Sivli-Embir** [comment]
See PR #2

**Comment by txs** [comment]
I will change your code and suggest you to do it this way.
I set the dynamic template on router and it works fine.
please set it in router.
eg.

BlazeLayout.render('globalLayout', { 
main: "projectIndex",
headerTitle: "headerTitleIndex",
headerButtonLeft: "",
headerButtonRight: "",

});

to pass the data context, what I would do is like this.

{{> ionNavBar self}}
Template.parentTemplate.helpers({
self: function(){
var self = this;
self.parentFunction = Template.parentData(1).headerTitle;
return self;
},
})

**Comment by txs** [comment]
Hi guys! I update the package to flow-route 2.6.2. Thanks for helping!

**Comment by johanbuys** [comment]
Awesome, Thanks!

**Comment by txs** [comment]
Np
2015年10月29日 下午6:18 於 "Johan Buys" notifications@github.com 寫道：
