### ISSUE TITLE
ContentFor Helpers in NavBar

### ISSUE THREAD

**Issue by ghost** [txs/meteor-wecare-ionic-flow#3]
Did you completely remove the ContentFor helpers for the NavBar? I know it was dependent on Iron Router, but did you provide an alternative? I only see the helpers commented out in ionNavBar.js.

**Comment by txs** [comment]
Yes! It's now Template.dynamic!
Please check the code https://github.com/txs/meteor-wecare-ionic-flow/blob/master/components/ionNavBar/ionNavBar.html

**Comment by ghost** [comment]
Perfect. Thanks.
