### ISSUE TITLE
Yield is not found

### ISSUE THREAD

**Issue by ouya99** [txs/meteor-wecare-ionic-flow#5]
I tried to add the package...
# meteoric:ionic

wecare:ionic-flow

and added the kadira-flow:router too, cause it was not found by default.

Exception in defer callback: Error: No such template: yield
Then the {{yield}} tag is not found.

Please help on what packages to use from the meteoric project and how to use FlowRouter here.

When using both meteoric and ionic-flow package together.. the FlowRouter is not found either. maybe because its omitted by the iron:router

Thanks
java99

**Comment by txs** [comment]
First, you don't need meteor:ionic package since the ionic-flow is the package for it.
Second, please learn flow-router. There's no yield in flow-router. FlowRouter layout is called blaze-layout https://github.com/kadirahq/blaze-layout

Good luck
